### ISSUE TITLE
'Converting circular structure to JSON' on invoke local

### ISSUE THREAD

**Issue by guerrerocarlos** [compwright/aws-serverless-koa#2]
Use basic example and execute:

`   serverless invoke local --function [functionName]`

Error:

```
  Type Error ---------------------------------------------

  Converting circular structure to JSON

  Stack Trace --------------------------------------------

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at AwsInvokeLocal.handleResult (.../.nvm/versions/node/v9.10.1/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:349:43)
    at AwsInvokeLocal.callback (.../.nvm/versions/node/v9.10.1/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:359:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by JimLynchCodes** [comment]
any fix for this?
